import Notiflix from 'notiflix';

Notiflix.Notify.init({
  width: '280px',
  position: 'center-bottom',
  distance: '20px',
  opacity: 1,
  borderRadius: '8px',
  rtl: false,
  timeout: 3000,
  messageMaxLength: 110,
  backOverlay: false,
  backOverlayColor: 'rgba(0,0,0,0.5)',
  plainText: true,
  showOnlyTheLastOne: false,
  clickToClose: false,
  pauseOnHover: true,
  ID: 'NotiflixNotify',
  className: 'notiflix-notify',
  zindex: 4001,
  fontFamily: 'Poppins',
  fontSize: '14px',
  cssAnimation: true,
  cssAnimationDuration: 400,
  cssAnimationStyle: 'from-right',
  closeButton: false,
  useIcon: true,
  useFontAwesome: false,
  fontAwesomeIconStyle: 'shadow',
  fontAwesomeIconSize: '34px',
  success: {
    background: '#9dc888',
    textColor: '#161616',
    childClassName: 'notiflix-notify-success',
    notiflixIconColor: 'rgba(16, 14, 14, 0.408)',
    fontAwesomeClassName: 'fas fa-check-circle',
    fontAwesomeIconColor: 'rgba(0,0,0,0.2)',
    backOverlayColor: 'rgba(50,198,130,0.2)',
  },
  failure: {
    background: '#e1584e',
    textColor: '#1c1c1cd0',
    childClassName: 'notiflix-notify-failure',
    notiflixIconColor: 'rgba(16, 14, 14, 0.408)',
    fontAwesomeClassName: 'fas fa-times-circle',
    fontAwesomeIconColor: 'rgba(0,0,0,0.2)',
    backOverlayColor: 'rgba(255,85,73,0.2)',
  },
  warning: {
    background: '#ffc001',
    textColor: '#161616',
    childClassName: 'notiflix-notify-warning',
    notiflixIconColor: 'rgba(16, 14, 14, 0.408)',
    fontAwesomeClassName: 'fas fa-exclamation-circle',
    fontAwesomeIconColor: 'rgba(0,0,0,0.2)',
    backOverlayColor: 'rgba(238,191,49,0.2)',
  },
  info: {
    background: '#26c0d3',
    textColor: '#161616',
    childClassName: 'notiflix-notify-info',
    notiflixIconColor: 'rgba(16, 14, 14, 0.408)',
    fontAwesomeClassName: 'fas fa-info-circle',
    fontAwesomeIconColor: 'rgba(0,0,0,0.2)',
    backOverlayColor: 'rgba(38,192,211,0.2)',
  },
});
